[package]
name = "testenv"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
anyhow = { workspace = true }
bdk_wallet = { workspace = true, features = ["test-utils"] }
bdk_electrum = { workspace = true }
rustls = { workspace = true }
axum = { version = "0.8.7" }
axum-reverse-proxy = { version = "1.0.3", default-features = false, features = ["rustls"] }
secp = { workspace = true }
electrsd = { version = "0.36.1", features = [
"esplora_a33e97e1",
"corepc-node_29_0",
] }
tokio = { workspace = true, features = [ "rt-multi-thread"]}
ureq = "2.12.1"

tempfile = "3.23.0"
simple-semaphore = "0.2.0"
once_cell = "1.21"
