[package]
name = "testenv"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
anyhow = { workspace = true }
axum = { version = "0.8.7" }
axum-embed = { version = "0.1.0"}
axum-reverse-proxy = { version = "1.0.3" }
bdk_wallet = { workspace = true }
electrsd = { version = "0.36.1", features = [
"esplora_a33e97e1",
"corepc-node_29_0",
] }
rust-embed = { version = "8.9.0"}
tokio = { workspace = true, features = [ "rt-multi-thread"]}
tower-http = { version = "0.6.7", features = [ "fs", "cors" ]}
