[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bdk_electrum = { workspace = true }
bdk_wallet = { workspace = true }
dotenv = "0.15.0"
musig2 = { workspace = true }
rand = { workspace = true }
